### ISSUE TITLE
Create users/me endpoint

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/FIRE-WS#12]
Refer to EyeSeeTea/FIRE-MockServer/issues/23

**Comment by ifoche** [comment]
@tokland I've talked a little bit with @MurhafSousli and the app's currently prepared to login against users/me endpoint, so we can use that as the userInfo endPoint instead of userInfo. That way we would reuse what's already implemented in the app. 

So users/me would provide the user with:
- Authentication (due to the basic auth that's implemented in the whole WS)
- His own profile info
- All the SIP information that the user could need. By now we said that only the kamailio hostname and maybe the kamailio port, but @MurhafSousli will maybe ask you through this issue to return also other information that he could need while implementing the SIPjs integration

Sounds good?

**Comment by tokland** [comment]
Sounds good! -- Mobile
