### ISSUE TITLE
NewUserRequest new business logic

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/FIRE-WS#15]
https://github.com/EyeSeeTea/FIRE-WS/wiki/Webservice

- [x] Create a request ID on each user request
- [x] When admin accepts it, the user request status changes (this is done) + create Notification [type=newUserAccepted] or Notification [type=newUserRejected] (with message)
- [x] Modify NewUserRequest endpoint to return the request UID.
```
api.add_resource(NewUserRequest, '/newUserRequests/<int:new_user_request_id>')
```

**Comment by jordibc** [comment]
Hm, I don't really understand the last point ("Modify NewUserRequest endpoint to return the request UID"). What exactly is it supposed to return? The User related to the request? It's id? The id of the request?

**Comment by jordibc** [comment]
After what we discussed this morning, I understand that we want to get the request id whenever we do a POST to `newUserRequests`, right?

But that's already happening:

```
curl -u joel:pass -H "Content-Type: application/json" \
  -X POST -d '{"user": {"name": "Nacho"}}' \
  http://localhost:5005/newUserRequests
```

gives

```
{
  "data": {
    "adminUser": null, 
    "created": "2017-10-20T11:19:10.015887+00:00", 
    "id": 5, 
    "state":  ...
```

where that `id` is already what we want. Isn't it?

**Comment by ifoche** [comment]
yes...I think so. So it would be done, then
