### ISSUE TITLE
Notifications treatment

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/FIRE-WS#19]

**Comment by ifoche** [comment]
- [x] Hardcode a notifications limit
- [x] Remove seen bool (only in wiki)

**Comment by jordibc** [comment]
What should happen when we reach that limit? Operations should work but no notifications are created? Maybe write a last notification explaining the problem? Or send an sms to alert?
 Operations should not fail then, I suppose!

As for the "remove seen bool", I'm afraid I forgot what that means...

**Comment by tokland** [comment]
> What should happen when we reach that limit?

This limit applies only to the ws response, there is no limit on the creation of notifications.  They should be returned in order "created DESC", I guess. There is already something done in my code, make sure it works as expected.

> As for the "remove seen bool"

I removed that flag already when porting to SQLAlchemy, nothing to do here. It was a flag to know if a user had already seen a notification. We'll keep it simple for now, no flag in the server.

**Comment by jordibc** [comment]
Awesome, thanks @tokland . I understand that the relevant part is the `per_page=50` in the `NotificationService` here:
```
return self.paginate(page=1, per_page=50, order_by=models.Notification.created)
```

That 50 would be our current hard-coded notification limit. So the only thing that is missing is to have a test for it, right?

**Comment by tokland** [comment]
A test for the limit and order would be great, yes!

**Comment by jordibc** [comment]
Ok, I added the test in branch `feature/notifications-limit`. I'm going to do a pull request now. Thanks!
