### ISSUE TITLE
Install Kamailio and create basic config

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/FIRE-WS#4]
Please follow as much as possible [this configuration](https://github.com/saycel/Saycel.Phone/tree/testing). We're trying to keep both projects in sync

**Comment by tokland** [comment]
`$ docker-compose up` did not work, but I've been able to setup Kamailio 5.0.3 from sources and make it work (no docker) with the `kamailio.cfg` found in this repo, create 2 users and make calls between 2 android devices using CSipSimple.

**Comment by ifoche** [comment]
Thanks @tokland. That config works. The goal here was to end up with something working using kamailio using as much as possible from that repo, so I think this task is perfectly done.

**Comment by ifoche** [comment]
Re-opening this issue to point to the installation of the basic kamailio in dev.eyeseetea.com. Thanks @tokland!

**Comment by tokland** [comment]
Installation process:

https://github.com/EyeSeeTea/FIRE-WS/wiki/Kamailio-setup

How to use it:

https://github.com/EyeSeeTea/FIRE-WS/wiki/Kamailio-setup#test-on-sip-phone

I created users 1 (password=1pass) and 2 (password=2pass), I can make calls between this two users using CSipSimple

**Comment by ifoche** [comment]
Thanks @tokland!
